name: EduCombat
description: Sistema de controle de pvp impondo algumas regras quando estiver em pvp
main: net.eduard.combat.Main
version: 1.0
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD