name: Template
description: Plugin Template
main: me.eduard.template.Main
version: 1.0
authors: [Eduard]
commands:
  teste:
    description: Comando test
    usage: /<command>
    alises: [test]
    permission: teste.test
    permission-message: Sem permissao