name: DoubleJump
description: Sistema de pulo duplo usando Espaco
main: net.eduard.doublejump.DoubleJump
version: 1.0
authors: [Eduard]
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  doublejumpreload:
    aliases: [dbj]
    description: Recarregar configuracoes do DoubleJump
  