name: Kit
description: Sistema de Criar kits e editar na config
main: net.eduard.kit.Main
version: 1.0
authors: [Eduard]
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  kits:
    description: Mostra os Kits
    usage: /<command> [player]
    permission: kit.list
  kit:
    description: Pega um Kit
    usage: /<command> [player]
    permission: kit.use
  setkit:
    description: Seta um Kit
    usage: /<command> [player]
    permission: kit.set