name: SkyWars
description: Plugin SkyWars
version: 1.0
main: net.eduard.skywars.Main
commands:
  skywars:
    description: Comando principal do plugin de skywars
    usage: /<command> help
    aliases: [sky,sw]
    