name: Template
description: "§2Plugin Template plugin exemplo"
main: net.eduard.template.Main
version: 1.0
author: Eduard
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  comando:
    aliases: [cmd]
    permission: perm.use
    permission-message: "Você não tem permissão para executar este comando."
    usage: /<command> [usage]
    description: "Descrição do Comando"
