name: EduComboCounter
description: Sistema de contar o seu combo feito
main: net.eduard.combocounter.Main
version: 1.0
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  combocounter:
    aliases: [hitcounter,tapacontador,contarhits]
    usage: /<command>
    description: Ativar ou desativar combo counter
