name: Tag
description: Sistema de manipulacao de Tags
main: net.eduard.tag.Main
version: 1.0
authors: [Eduard]
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  tag:
    aliases: [gettag]
    usage: /<command> <tag>
    description: Escolha um Tag
  tags:
    aliases: [taglist,listtag]
    description: Lista as Tags
  settag:
    aliases: [createtag]
    usage: /<command> <prefix> [suffix]
    description: Cria uma Tag
  deletetag:
    aliases: [deltag]
    usage: /<command> <tag>
    description: Deleta uma Tag
  tagreload:
    aliases: [tagrl]
    usage: /<command> <tag>
    description: Recarrega as Tags