name: EduSpawn
description: Sistema de Spawn configuravel
main: net.eduard.spawn.SpawnPlugin
version: 1.0
authors: [Eduard]
author: Eduard
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  spawn:
    description: Teleportar para o Spawn
    permission: spawn.use
    usage: /<command>
  setspawn:
    usage: /<command>
    permission: spawn.set
    description: Setar o Spawn