name: Warp
description: Sistema de Warps(Teleportes)
main: net.eduard.warp.Main
version: 1.0
authors: [Eduard]
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  warps:
    aliases: [warplist]
    usage: /<command> <warp>
    description: Ver a lista de Warps existentes
  warp:
    usage: /<command> <warp>
    description: Teleportar para um Warp
  deletewarp:
    aliases: [delwarp]
    usage: /<command> <warp>
    description: Deleta um Warp
  setwarp:
    usage: /<command> <warp>
    description: Cria um Warp
  warpreload:
    aliases: [wr]
    description: Recarrega warps da Config
  warpmenu:
    aliases: [menuwarp]
    description: Salva warps da Config