name: eDinheiro
description: Sistema de moedas pro servidor basico
main: net.eduard.dinheiro.Main
version: 1.0
authors: [Eduard]
author: Eduard
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  money:
