name: zLuckHG
main: zLuck.zMain.zLuck
author: zLuck_Dev
version: 1.0

commands:
  tempo:
  invsee:
  arena:
  bc:
  cm:
  desistir:
  fly:
  forceminifeast:
  forcefeast:
  gm:
  head:
  game:
  ping:
  score:
  spawn:
  s:
  tp:
  tpall:
  puxar:
  tell:
  kit:
  youtuber:
  yt:
  skit:
  admin: