name: HG
description: Plugin de HG desenvolvido por Eduard com Colaborador Vitor
main: net.eduard.hg.Main
version: 1.0
authors: [Eduard]
depends: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  staffchat:
    aliases: [chatdastaff,cs,sc]
    description: Conversar com jogadores Staff
  toggleonline:
    aliases: [Invs,Vis,hide,show,aparecer,sumir,esconder,desaparecer]
    description: Aparecer ou Desaparecer do Server
  tooglekit:
    aliases: [enablekits,disablekits]
    description: Ativar ou Desativar uso de Kits
  teleportall:
    aliases: [tpall]
    description: Teleporta todos ate voce
  cleardrops:
    aliases: [limpardrops]
    description: Remove todos os drops
  kit:
    usage: /<command> <kit>
    description: Selecione um kit
  skit:   


