name: EduardAPI
description: A melhor API ja criada pelo Eduard
main: net.eduard.eduardapi.Main
version: 1.0
authors: [Eduard]
soft-depend: [Essentials,Vault]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  eduard:
    description: Comando pricipal da API
    aliases: [api,e]
    usage: /<command> help
  goto:
    description: Teleportar para um Mundo
    aliases: [world]
    usage: /<command> <world>
  gamemode:
    description: Trocar o Modo de Jogo
    aliases: [gm,mode]
    usage: /<command> [0-3] [player]
