name: EduardAPI
description: A melhor API ja criada pelo Eduard
main: net.eduard.eduardapi.EduardAPI
version: 1.0
authors: [Eduard]
soft-depend: [Essentials,Vault]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  map: 
    description: Controle dos Mapas da API
    aliases: [mapa]
    usage: /<command> help
  goto:
    description: Teleportar para um Mundo
    aliases: [world,go]
    usage: /<command> <world>
  config:
    description: Controle das Configs da API
    aliases: [configs,config]
    usage: /<command> help
  api:
    description: Comando principal da API
    aliases: [eduardapi,eduard,e]
    usage: /<command> help
  