name: EduardAntBot
description: Sistema Ant Login de Bot usando Proxy de uma config para saber quem eh Proxy
main: net.eduard.antbot.Main
version: 1.0
authors: [Eduard]
author: Eduard
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD