name: MegaPvP
description: Plugin de KitPvP
main: mega.plugins.kitpvp.Main
version: 1.0
authors: [Eduard,KyzeYT]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  comando:
    aliases: [dg]
    permission: perm.use
    permission-message: No Permission
    usage: /<command> [usage]
    description: Comando Description
